name: Node.js CI

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - development
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      NODE_ENV: 'test'

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install --legacy-peer-deps
    - run: npm test
